desc_columnas=[
    {"hotel": "Los conjuntos de datos contienen la información de reservas de dos hoteles. Uno de ellos es un complejo hotelero y el otro es un hotel urbano."},
    {"is_canceled": "Valor que indica si la reserva fue cancelada (1) o no (0)."},
    {"lead_time": "Número de días transcurridos entre la fecha de entrada de la reserva en el PMS y la fecha de llegada."},
    {"arrival_date_year": "Año de fecha de llegada"},
    {"arrival_date_month": "Mes de fecha de llegada con 12 categorías: “Enero” a “Diciembre”"},
    {"arrival_date_week_number": "Número de semana de la fecha de llegada"},
    {"arrival_date_day_of_month": "Día del mes de la fecha de llegada"},
    {"stays_in_weekend_nights": "Número de noches de fin de semana (sábado o domingo) que el huésped se alojó o reservó para alojarse en el hotel"},
    {"stays_in_week_nights": "Número de noches de la semana (de lunes a viernes) que el huésped se alojó o reservó para alojarse en el hotel BO y BL/Calculado contando el número de noches de la semana"},
    {"adults": "Número de adultos"},
    {"children": "Número de niños"},
    {"babies": "Número de bebés"},
    {"meal": "Tipo de alojamiento"},
    {"country": "Pais natal."},
    {"market_segment": "Designación de segmento de mercado. En las categorías, el término “TA” significa “Agentes de Viajes” y “TO” significa “Operadores Turísticos”."},
    {"distribution_channel": "Canal de distribución de reservas. El término “TA” significa “Agentes de Viajes” y “TO” significa “Operadores Turísticos”"},
    {"is_repeated_guest": "Valor que indica si el nombre de la reserva era de un huésped repetido (1) o no (0)"},
    {"previous_cancellations": "Número de reservas anteriores que fueron canceladas por el cliente antes de la reserva actual."},
    {"previous_bookings_not_canceled": "Número de reservas anteriores no canceladas por el cliente antes de la reserva actual."},
    {"reserved_room_type*": "Código del tipo de habitación reservada. Se indica el código en lugar de la denominación por razones de anonimato."},
    {"assigned_room_type": "Código del tipo de habitación asignada a la reserva. En ocasiones, el tipo de habitación asignada difiere del tipo de habitación reservada por razones operativas del hotel (por ejemplo, overbooking) o por petición del cliente. Se presenta el código en lugar de la designación por razones de anonimato."},
    {"booking_changes": "Número de cambios/modificaciones realizadas en la reserva desde el momento en que se introdujo la reserva en el PMS hasta el momento del check-in o cancelación."},
    {"deposit_type": "Sin depósito: no se realizó ningún depósito; Sin reembolso: se realizó un depósito por el valor del costo total de la estadía; Reembolsable: se realizó un depósito por un valor inferior al costo total de la estadía."},
    {"agent": "Identificación de la agencia de viajes que realizó la reserva"},
    {"company": "Identificación de la empresa/entidad que ha realizado la reserva o que ha sido responsable del pago de la misma. Se presenta la identificación en lugar de la designación por razones de anonimato."},
    {"days_in_waiting_list": "Número de días que la reserva estuvo en lista de espera antes de ser confirmada al cliente."},
    {"customer_type": ""},
    {"adr": "Tarifa diaria promedio (calculada dividiendo la suma de todas las transacciones de alojamiento por el número total de noches de estadía)"},
    {"required_car_parking_spaces": "Número de plazas de aparcamiento solicitadas por el cliente"},
    {"total_of_special_requests": "Número de peticiones especiales realizadas por el cliente (p. ej. cama doble o piso alto)"},
    {"reservation_status": "Check-Out: el cliente se registró pero ya se fue; No-Show: el cliente no se registró y no informó al hotel el motivo."},
    {"reservation_status_date": "Fecha en la que se estableció el último estado. Esta variable se puede utilizar junto con ReservationStatus para saber cuándo se canceló la reserva o cuándo el cliente abandonó el hotel.	"},
    {"name": "Nombre del Invitado (No Real)."},
    {"email": "Correo electrónico (No Real)."},
    {"phone-number": "Número de teléfono (No Real)"},
    {"credit_card": "Número de tarjeta de crédito (No Real)"}
]